if #tools[{state.currentTool}].name == 9 ; If this tool is a spindle...
    while iterations < #spindles ; ...loop over all defined spindles.
        if state.currentTool == spindles[{iterations}].tool ; If we find a spindle associated with the current tool...
            M4 P{iterations} S800 ; ...set it to 800 RPM, counterclockwise.
